// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpyxnwcxfpqiinncqswe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxweXhud2N4ZnBxaWlubmNxc3dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0NzEyMDQsImV4cCI6MjA1MTA0NzIwNH0.L15l4DTAUBM0PKf_WhQS6jalXF-54lDlH_VVRvTa9jo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);